### ISSUE TITLE
欢迎大家提issue!

### ISSUE THREAD

**Issue by yenche123** [yenche123/cb-privacy#3]
如题 :tada: :tada:
欢迎大家跟我交流~

**Comment by 184845307** [comment]
![图片](https://user-images.githubusercontent.com/88465383/235697777-2b505972-b81e-412e-96ba-b1e8aa912674.png)
在数据分析者那里怎么点击不进去呢

**Comment by 184845307** [comment]
![图片](https://user-images.githubusercontent.com/88465383/235698249-511e144e-e583-4b27-9c4d-6215c824450b.png)
终端设备这里也出现小错误

**Comment by 184845307** [comment]
好像是cb函数无法上传到云端   大佬这是怎么回事
![图片](https://user-images.githubusercontent.com/88465383/235703123-20d82f99-cc2a-43e0-8e56-3d34e4808667.png)

**Comment by yenche123** [comment]
> ![图片](https://user-images.githubusercontent.com/88465383/235697777-2b505972-b81e-412e-96ba-b1e8aa912674.png) 在数据分析者那里怎么点击不进去呢

@184845307 
在 `identity.js` 第 17 行的位置会打印出自己的 `openid`，在第 19 行处修改成自己的。
![image](https://user-images.githubusercontent.com/28533125/235706799-1c16f88e-41fc-4456-a836-c85c8167970b.png)

**Comment by yenche123** [comment]
> 好像是cb函数无法上传到云端 大佬这是怎么回事 ![图片](https://user-images.githubusercontent.com/88465383/235703123-20d82f99-cc2a-43e0-8e56-3d34e4808667.png)

已解决。另外，遇到问题请新开 issue。

**Comment by 184845307** [comment]
请问一下openID怎么获取呢  我在网上找的方法都不太行
![图片](https://user-images.githubusercontent.com/88465383/235823303-2213d569-0a58-4f6d-8a86-04cade3d51f7.png)
